name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build -t barellano/docker-react -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI-true barellano/docker-react npm run test:ci
